version: '3.8'

services:
  memory-service:
    container_name: memory
    build: ./
    ports:
      - "8082:8082"
    environment:
      KAFKA_BROKERS: "kafka:9092"
      POSTGRES_HOST: "postgres_dock"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "memory"
    networks:
      - global-network

networks:
  global-network:
    external: true 