// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: submodule-food-delivery/order/basket.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Basket represents a user's order basket.
type Basket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "OPEN", "CLOSED", "COMPLETED"
}

func (x *Basket) Reset() {
	*x = Basket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Basket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Basket) ProtoMessage() {}

func (x *Basket) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Basket.ProtoReflect.Descriptor instead.
func (*Basket) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{0}
}

func (x *Basket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Basket) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Basket) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// BasketRequest is used for various basket related gRPC methods.
type BasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BasketRequest) Reset() {
	*x = BasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketRequest) ProtoMessage() {}

func (x *BasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketRequest.ProtoReflect.Descriptor instead.
func (*BasketRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{1}
}

func (x *BasketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CreateBasketRequest is used for creating a new basket for a user.
type CreateBasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basket *Basket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *CreateBasketRequest) Reset() {
	*x = CreateBasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketRequest) ProtoMessage() {}

func (x *CreateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBasketRequest) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

// UpdateBasketRequest is used for updating an existing basket.
type UpdateBasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Basket *Basket `protobuf:"bytes,1,opt,name=basket,proto3" json:"basket,omitempty"`
}

func (x *UpdateBasketRequest) Reset() {
	*x = UpdateBasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasketRequest) ProtoMessage() {}

func (x *UpdateBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasketRequest.ProtoReflect.Descriptor instead.
func (*UpdateBasketRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBasketRequest) GetBasket() *Basket {
	if x != nil {
		return x.Basket
	}
	return nil
}

// PatchBasketRequest is used for partially updating an existing basket.
type PatchBasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "OPEN", "CLOSED", "COMPLETED"
}

func (x *PatchBasketRequest) Reset() {
	*x = PatchBasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatchBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBasketRequest) ProtoMessage() {}

func (x *PatchBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBasketRequest.ProtoReflect.Descriptor instead.
func (*PatchBasketRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{4}
}

func (x *PatchBasketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatchBasketRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PatchBasketRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetBasketRequest is used for retrieving a basket by its ID.
type GetBasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetBasketRequest) Reset() {
	*x = GetBasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketRequest) ProtoMessage() {}

func (x *GetBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketRequest.ProtoReflect.Descriptor instead.
func (*GetBasketRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{5}
}

func (x *GetBasketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetBasketByUserRequest is used for retrieving a user's basket.
type GetBasketByUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetBasketByUserRequest) Reset() {
	*x = GetBasketByUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketByUserRequest) ProtoMessage() {}

func (x *GetBasketByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketByUserRequest.ProtoReflect.Descriptor instead.
func (*GetBasketByUserRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{6}
}

func (x *GetBasketByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteBasketRequest is used for deleting a basket.
type DeleteBasketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBasketRequest) Reset() {
	*x = DeleteBasketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketRequest) ProtoMessage() {}

func (x *DeleteBasketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketRequest.ProtoReflect.Descriptor instead.
func (*DeleteBasketRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBasketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBasketRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteBasketRes) Reset() {
	*x = DeleteBasketRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketRes) ProtoMessage() {}

func (x *DeleteBasketRes) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketRes.ProtoReflect.Descriptor instead.
func (*DeleteBasketRes) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBasketRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// BasketItem represents a single item in a user's basket.
type BasketItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BasketId  string `protobuf:"bytes,2,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"`
	ProductId string `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity  int32  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"` // Add more fields as needed (e.g., options, special instructions)
}

func (x *BasketItem) Reset() {
	*x = BasketItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketItem) ProtoMessage() {}

func (x *BasketItem) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketItem.ProtoReflect.Descriptor instead.
func (*BasketItem) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{9}
}

func (x *BasketItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BasketItem) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *BasketItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BasketItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// CreateBasketItemRequest is used for adding a product to a basket.
type CreateBasketItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketItem *BasketItem `protobuf:"bytes,1,opt,name=basket_item,json=basketItem,proto3" json:"basket_item,omitempty"`
}

func (x *CreateBasketItemRequest) Reset() {
	*x = CreateBasketItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBasketItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBasketItemRequest) ProtoMessage() {}

func (x *CreateBasketItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBasketItemRequest.ProtoReflect.Descriptor instead.
func (*CreateBasketItemRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBasketItemRequest) GetBasketItem() *BasketItem {
	if x != nil {
		return x.BasketItem
	}
	return nil
}

// GetBasketItemsRequest is used for retrieving all items in a basket.
type GetBasketItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketId string `protobuf:"bytes,1,opt,name=basket_id,json=basketId,proto3" json:"basket_id,omitempty"`
}

func (x *GetBasketItemsRequest) Reset() {
	*x = GetBasketItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketItemsRequest) ProtoMessage() {}

func (x *GetBasketItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketItemsRequest.ProtoReflect.Descriptor instead.
func (*GetBasketItemsRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{11}
}

func (x *GetBasketItemsRequest) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

// GetBasketItemsResponse is used for returning a list of basket items.
type GetBasketItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasketItems []*BasketItem `protobuf:"bytes,1,rep,name=basket_items,json=basketItems,proto3" json:"basket_items,omitempty"`
}

func (x *GetBasketItemsResponse) Reset() {
	*x = GetBasketItemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBasketItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBasketItemsResponse) ProtoMessage() {}

func (x *GetBasketItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBasketItemsResponse.ProtoReflect.Descriptor instead.
func (*GetBasketItemsResponse) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{12}
}

func (x *GetBasketItemsResponse) GetBasketItems() []*BasketItem {
	if x != nil {
		return x.BasketItems
	}
	return nil
}

// DeleteBasketItemRequest is used for deleting a basket item.
type DeleteBasketItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteBasketItemRequest) Reset() {
	*x = DeleteBasketItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketItemRequest) ProtoMessage() {}

func (x *DeleteBasketItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteBasketItemRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteBasketItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBasketItemRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DeleteBasketItemRes) Reset() {
	*x = DeleteBasketItemRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBasketItemRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBasketItemRes) ProtoMessage() {}

func (x *DeleteBasketItemRes) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBasketItemRes.ProtoReflect.Descriptor instead.
func (*DeleteBasketItemRes) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteBasketItemRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateBasketItemQuantityRequest is used for updating the quantity of a product in a basket item.
type UpdateBasketItemQuantityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *UpdateBasketItemQuantityRequest) Reset() {
	*x = UpdateBasketItemQuantityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBasketItemQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasketItemQuantityRequest) ProtoMessage() {}

func (x *UpdateBasketItemQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_submodule_food_delivery_order_basket_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasketItemQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateBasketItemQuantityRequest) Descriptor() ([]byte, []int) {
	return file_submodule_food_delivery_order_basket_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBasketItemQuantityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBasketItemQuantityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_submodule_food_delivery_order_basket_proto protoreflect.FileDescriptor

var file_submodule_food_delivery_order_basket_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x73, 0x75, 0x62, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x66, 0x6f, 0x6f, 0x64,
	0x2d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x22, 0x49, 0x0a, 0x06, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1f,
	0x0a, 0x0d, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x3c, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22, 0x3c, 0x0a,
	0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x52, 0x06, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22, 0x55, 0x0a, 0x12, 0x50,
	0x61, 0x74, 0x63, 0x68, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2b, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x74, 0x0a,
	0x0a, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x22, 0x4d, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32,
	0x0a, 0x0b, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0a, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x22, 0x34, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x62, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x62, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x4d, 0x0a, 0x1f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x32, 0xc6, 0x05, 0x0a, 0x0d, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x22, 0x00, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12,
	0x14, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0b, 0x50, 0x61, 0x74, 0x63, 0x68, 0x42,
	0x61, 0x73, 0x6b, 0x65, 0x74, 0x12, 0x19, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x61,
	0x74, 0x63, 0x68, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x22,
	0x00, 0x12, 0x44, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x12, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00,
	0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x1c, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x73, 0x6b,
	0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61, 0x73,
	0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12,
	0x26, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x61,
	0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x42, 0x61, 0x73, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e,
	0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_submodule_food_delivery_order_basket_proto_rawDescOnce sync.Once
	file_submodule_food_delivery_order_basket_proto_rawDescData = file_submodule_food_delivery_order_basket_proto_rawDesc
)

func file_submodule_food_delivery_order_basket_proto_rawDescGZIP() []byte {
	file_submodule_food_delivery_order_basket_proto_rawDescOnce.Do(func() {
		file_submodule_food_delivery_order_basket_proto_rawDescData = protoimpl.X.CompressGZIP(file_submodule_food_delivery_order_basket_proto_rawDescData)
	})
	return file_submodule_food_delivery_order_basket_proto_rawDescData
}

var file_submodule_food_delivery_order_basket_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_submodule_food_delivery_order_basket_proto_goTypes = []any{
	(*Basket)(nil),                          // 0: order.Basket
	(*BasketRequest)(nil),                   // 1: order.BasketRequest
	(*CreateBasketRequest)(nil),             // 2: order.CreateBasketRequest
	(*UpdateBasketRequest)(nil),             // 3: order.UpdateBasketRequest
	(*PatchBasketRequest)(nil),              // 4: order.PatchBasketRequest
	(*GetBasketRequest)(nil),                // 5: order.GetBasketRequest
	(*GetBasketByUserRequest)(nil),          // 6: order.GetBasketByUserRequest
	(*DeleteBasketRequest)(nil),             // 7: order.DeleteBasketRequest
	(*DeleteBasketRes)(nil),                 // 8: order.DeleteBasketRes
	(*BasketItem)(nil),                      // 9: order.BasketItem
	(*CreateBasketItemRequest)(nil),         // 10: order.CreateBasketItemRequest
	(*GetBasketItemsRequest)(nil),           // 11: order.GetBasketItemsRequest
	(*GetBasketItemsResponse)(nil),          // 12: order.GetBasketItemsResponse
	(*DeleteBasketItemRequest)(nil),         // 13: order.DeleteBasketItemRequest
	(*DeleteBasketItemRes)(nil),             // 14: order.DeleteBasketItemRes
	(*UpdateBasketItemQuantityRequest)(nil), // 15: order.UpdateBasketItemQuantityRequest
}
var file_submodule_food_delivery_order_basket_proto_depIdxs = []int32{
	0,  // 0: order.CreateBasketRequest.basket:type_name -> order.Basket
	0,  // 1: order.UpdateBasketRequest.basket:type_name -> order.Basket
	9,  // 2: order.CreateBasketItemRequest.basket_item:type_name -> order.BasketItem
	9,  // 3: order.GetBasketItemsResponse.basket_items:type_name -> order.BasketItem
	2,  // 4: order.BasketService.CreateBasket:input_type -> order.CreateBasketRequest
	1,  // 5: order.BasketService.GetBasket:input_type -> order.BasketRequest
	6,  // 6: order.BasketService.GetBasketByUser:input_type -> order.GetBasketByUserRequest
	3,  // 7: order.BasketService.UpdateBasket:input_type -> order.UpdateBasketRequest
	4,  // 8: order.BasketService.PatchBasket:input_type -> order.PatchBasketRequest
	7,  // 9: order.BasketService.DeleteBasket:input_type -> order.DeleteBasketRequest
	10, // 10: order.BasketService.CreateBasketItem:input_type -> order.CreateBasketItemRequest
	11, // 11: order.BasketService.GetBasketItems:input_type -> order.GetBasketItemsRequest
	13, // 12: order.BasketService.DeleteBasketItem:input_type -> order.DeleteBasketItemRequest
	15, // 13: order.BasketService.UpdateBasketItemQuantity:input_type -> order.UpdateBasketItemQuantityRequest
	0,  // 14: order.BasketService.CreateBasket:output_type -> order.Basket
	0,  // 15: order.BasketService.GetBasket:output_type -> order.Basket
	0,  // 16: order.BasketService.GetBasketByUser:output_type -> order.Basket
	0,  // 17: order.BasketService.UpdateBasket:output_type -> order.Basket
	0,  // 18: order.BasketService.PatchBasket:output_type -> order.Basket
	8,  // 19: order.BasketService.DeleteBasket:output_type -> order.DeleteBasketRes
	9,  // 20: order.BasketService.CreateBasketItem:output_type -> order.BasketItem
	12, // 21: order.BasketService.GetBasketItems:output_type -> order.GetBasketItemsResponse
	14, // 22: order.BasketService.DeleteBasketItem:output_type -> order.DeleteBasketItemRes
	9,  // 23: order.BasketService.UpdateBasketItemQuantity:output_type -> order.BasketItem
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_submodule_food_delivery_order_basket_proto_init() }
func file_submodule_food_delivery_order_basket_proto_init() {
	if File_submodule_food_delivery_order_basket_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_submodule_food_delivery_order_basket_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Basket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*PatchBasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetBasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetBasketByUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBasketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBasketRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BasketItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CreateBasketItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GetBasketItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetBasketItemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBasketItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBasketItemRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_submodule_food_delivery_order_basket_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateBasketItemQuantityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_submodule_food_delivery_order_basket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_submodule_food_delivery_order_basket_proto_goTypes,
		DependencyIndexes: file_submodule_food_delivery_order_basket_proto_depIdxs,
		MessageInfos:      file_submodule_food_delivery_order_basket_proto_msgTypes,
	}.Build()
	File_submodule_food_delivery_order_basket_proto = out.File
	file_submodule_food_delivery_order_basket_proto_rawDesc = nil
	file_submodule_food_delivery_order_basket_proto_goTypes = nil
	file_submodule_food_delivery_order_basket_proto_depIdxs = nil
}
